<?php

use Drupal\Core\Entity\EntityInterface;

/**
 * Implements hook_devel_generate_populated_fields_alter().
 */
function gogo_devel_generate_populate_fields_alter(EntityInterface $entity) {
  if ($entity->getEntityTypeId() === 'node') {
    if ($entity->bundle() === 'office') {
      $pre_phone = sprintf('+1 (%d) %d', rand(111,999), rand(111,999));
      $entity->field_tel->value = sprintf('%s-%d', $pre_phone, rand(1111,9999));
      $entity->field_fax->value = sprintf('%s-%d', $pre_phone, rand(1111,9999));
      $v = $entity->field_address->value;
      $entity->field_address->value = sprintf(
        "%s, %d\n%s\n%d %s\n%s",
        trim(substr($v,0,rand(12,20))),
        rand(1, 999),
        trim(substr($v,20,rand(6,10))),
        rand(11111, 999999),
        trim(substr($v,30,rand(6,12))),
        $entity->field_country->entity->name->value
      );
    }
    if ($entity->bundle() === 'article') {
      $entity->field_teaser_text->value = substr($entity->field_teaser_text->value, 0, 300);
    }
    if ($entity->bundle() === 'news') {
      $trimmed = substr($entity->body->value, 0, 300);
      $entity->set('body', [
        'value' => $trimmed,
        'summary' => $trimmed,
        'format' => 'plain_text'
      ]);
    }
  }
}

/**
 * A Util to render views.
 *
 * @param string $view_id
 * @param string $display_id
 */
function _gogo_render_view($view_id, $display_id) {
  $view = \Drupal::entityTypeManager()
    ->getStorage('view')
    ->load($view_id)
    ->getExecutable();
  $view->initDisplay();
  $view->setDisplay($display_id);
  $view->execute();
  return $view->render();
}

/**
 * Implements hook_preprocess_paragraph__PARAGRAPH_ID().
 */
function gogo_preprocess_paragraph__articles_news(&$variables) {
  $variables['articles'] = _gogo_render_view('articles', 'latest');
  $variables['news'] = _gogo_render_view('news', 'latest');
}

/**
 * Implements hook_preprocess_paragraph__PARAGRAPH_ID().
 */
function gogo_preprocess_paragraph__text_image(&$variables) {
  $variables['image_left'] = $variables['elements']['#paragraph']->field_swap_position->value === "0";
}

/**
 * Implements hook_theme().
 */
function gogo_theme($existing, $type, $theme, $path) {
  return [
    'header_banner' => [
      'variables' => [
        'image' => '',
        'title' => '',
      ],
      'template' => 'header-banner',
    ],
  ];
}
